# Generated by Django 3.0.4 on 2020-03-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='teamname',
            new_name='name',
        ),
    ]
